### PR TITLE
Add CI pipeline to automatically format code

### PR DESCRIPTION
**Pull request by simosathan9**
This PR introduces a CI pipeline to automatically format code using Prettier. In the PR there are also included the repository files modified through the CI pipeline that is introduced. For any changes required please let me know.

### CODE REVIEW

**Review by dspinellis — CHANGES_REQUESTED** [review]
Nice! Not sure if _prettier_ should be making changes as part of the CI. My approach would be to fail the CI if changes are needed, and have developers make them. This has the advantage that commits are associated with the developers that wrote the code.  However, if you've found your approach as a best practice I'm open to discuss it

**Review by dspinellis — CHANGES_REQUESTED** [review]
Also, I don't think we should be committing the `node_modules` directory. It weights down the repo for something that users can easily install on their own.

**Comment by simosathan9** [comment]
I faced a dilemma on whether the CI should fail and have the developers fix the styling issues or auto-format the code. I decided to choose the second approach because I thought that as long as the functional changes will be associated with the developers that wrote the code and only the formatting changes will be credited to the CI automation, then it would decrease the manual efforts required to fix the styling issues. However, it is quite simple to make the workflow fail in such cases and not auto-format the code so if you think that it is a better approach I will change this.

**Comment by simosathan9** [comment]
> > I faced a dilemma on whether the CI should fail and have the developers fix the styling issues or auto-format the code. I decided to choose the second approach because I thought that as long as the functional changes will be associated with the developers that wrote the code and only the formatting changes will be credited to the CI automation, then it would decrease the manual efforts required to fix the styling issues. However, it is quite simple to make the workflow fail in such cases and not auto-format the code so if you think that it is a better approach I will change this.
> 
> The problem with automatic changes is that `git blame` will not associate them by default with the person who made the actual change. So since you're also on the fence, let's got for a failing CI. We can provide instructions for a pre-commit action that developers can use to format the code before the commit.

I have created a pre-commit hook that runs the prettier check command and in case that there exist styling errors it suggests to the developer to run the `npm run prettier-fix` command (prettier-fix script runs prettier --write . command). How could I commit the pre-commit hook since it is not getting tracked ?. Would it be a good practice to have a .githooks directory that contains the pre-commit hook and then have the developers run a script that copies that hook within the .git/hooks directory ?

**Comment by dspinellis** [comment]
I don't know of a good way to do this.  In another project [I documented it as part of the development processes](https://dspinellis.github.io/alexandria3k/dev.html). You can add similar instructions in a `README.md` section.

**Pull request closed without merging**
